# Uncomment the next line to define a global platform for your project
 platform :ios, '10.0'

target 'Example' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
	pod 'SROTPView', :path => "/Users/sarojraut/SROTPView/Example"
  # Pods for Example

  target 'ExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ExampleUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
